server:
  port: 1111
  
spring:
  application:
    name: Airport-service
    
  data:
    mongodb:
      uri: mongodb+srv://Megha-nancy:megha@test.vkqxd.mongodb.net/FlightBooking?retryWrites=true&w=majority

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka  